<a href="https://colab.research.google.com/github/Korchomnyi-Ivan/Korchomnyi-Ivan-Machine-3-15/blob/main/%D0%9B%D0%A0_1_%D0%9A%D0%BE%D1%80%D1%87%D0%BE%D0%BC%D0%BD%D0%BE%D0%B3%D0%BE_%D0%86_%D0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Був присутній на парі

In [ ]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
matrix = np.random.randint(1,6,size=(3,3))

matrix

array([[5, 4, 3],
       [5, 3, 2],
       [1, 3, 2]])

In [ ]:
det = np.linalg.det(matrix)
det

np.float64(4.000000000000002)

In [ ]:
product = np.prod(matrix)
product

np.int64(10800)

In [ ]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(10800)

In [ ]:
np.sum(matrix)

np.int64(28)

In [ ]:
np.max(matrix)

np.int64(5)

In [ ]:
np.min(matrix)

np.int64(1)

In [ ]:
np.mean(matrix)

np.float64(3.111111111111111)

In [ ]:
sqrt_matrix = np.sqrt(matrix)

print("Матриця квадратних коренів")
print(sqrt_matrix)

Матриця квадратних коренів
[[2.23606798 2.         1.73205081]
 [2.23606798 1.73205081 1.41421356]
 [1.         1.73205081 1.41421356]]


In [ ]:
row_sums = np.sum(matrix, axis=1).reshape(-1,1)

print("Сума елементів кожного рядка:")
print(row_sums)


Сума елементів кожного рядка:
[[12]
 [10]
 [ 6]]


In [ ]:
matrix.sum(axis=1).reshape(-1,1)

array([[12],
       [10],
       [ 6]])

In [ ]:
x = np.matrix([[1,2],[4,3]])
x

matrix([[1, 2],
        [4, 3]])

In [ ]:
x.sum(axis=1)

matrix([[3],
        [7]])

In [ ]:
x.sum(axis=1, dtype='float')

matrix([[3.],
        [7.]])

In [ ]:
vector = np.random.randint(0,10,size=25)
vector

array([7, 9, 6, 1, 4, 4, 5, 7, 7, 5, 4, 9, 2, 6, 0, 5, 1, 8, 8, 2, 3, 0,
       9, 5, 2])

In [ ]:
sorted_vector = np.sort(vector)[::-1]
sorted_vector

array([9, 9, 9, 8, 8, 7, 7, 7, 6, 6, 5, 5, 5, 5, 4, 4, 4, 3, 2, 2, 2, 1,
       1, 0, 0])

In [ ]:
from scipy import stats

mode = stats.mode(vector)

median = np.median(vector)

mean = np.mean(vector)

max_value = np.max(vector)

min_value = np.min(vector)

print("Мода:",mode)
print("Медіана:",median)
print("Середнє:",mean)
print("Максимальне значення:",max_value)
print("Мінімальне значення:",min_value)


Мода: ModeResult(mode=np.int64(5), count=np.int64(4))
Медіана: 5.0
Середнє: 4.76
Максимальне значення: 9
Мінімальне значення: 0


In [ ]:
matrix1 = np.random.randint(1,11,size=(4,4))
matrix2 = np.random.randint(1,11,size=(4,4))

print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)


Матриця 1:
[[7 2 9 8]
 [4 5 8 5]
 [7 1 6 9]
 [2 7 9 8]]

Матриця 2:
[[ 1  9  1  1]
 [10  7  7  7]
 [ 8  1  3  2]
 [ 4  1  8  5]]


In [ ]:
matrix_sum = matrix1 + matrix2

matrix_diff = matrix1 - matrix2

matrix_product = matrix1 * matrix2

matrix_division = np.divide(matrix1, matrix2, where=(matrix2!=0))

print("\nmatrix_sum")
print(matrix_sum)

print("\nmatrix_diff")
print(matrix_diff)

print("\nmatrix_product")
print(matrix_product)

print("\nmatrix_division")
print(matrix_division)


matrix_sum
[[ 8 11 10  9]
 [14 12 15 12]
 [15  2  9 11]
 [ 6  8 17 13]]

matrix_diff
[[ 6 -7  8  7]
 [-6 -2  1 -2]
 [-1  0  3  7]
 [-2  6  1  3]]

matrix_product
[[ 7 18  9  8]
 [40 35 56 35]
 [56  1 18 18]
 [ 8  7 72 40]]

matrix_division
[[7.         0.22222222 9.         8.        ]
 [0.4        0.71428571 1.14285714 0.71428571]
 [0.875      1.         2.         4.5       ]
 [0.5        7.         1.125      1.6       ]]


In [ ]:
x = np.arange(9.)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
x1 = x.reshape((3,3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
x2 = np.arange(3.)
x2

array([0., 1., 2.])

In [ ]:
#Операція трансляції векторів
np.multiply(x1,x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [ ]:
x1 = np.arange(6)
x1

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.power(x1,3)

array([  0,   1,   8,  27,  64, 125])

In [ ]:
x2 = np.array([1,2,3,3,2,1])
x1 = np.arange(6)
x1 ** x2

array([ 0,  1,  8, 27, 16,  5])

**Частина 2**

In [ ]:
vector = np.array([1,2,3,4,5])

vector

array([1, 2, 3, 4, 5])

In [ ]:
v1 = np.matrix([1,2,3,4,5])

v1

matrix([[1, 2, 3, 4, 5]])

In [ ]:
v2 = v1.T
v2

matrix([[1],
        [2],
        [3],
        [4],
        [5]])

In [ ]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

Два методи перевороту

In [ ]:
#1
v[::-1]

array([5, 4, 3, 2, 1])

In [ ]:
#2
v = np.flip(v)

v

array([5, 4, 3, 2, 1])

In [ ]:
np.mean(v)

np.float64(3.0)

In [ ]:
np.max(v)

np.int64(5)

In [ ]:
np.min(v)

np.int64(1)

In [ ]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

In [ ]:
v1

array([1, 2, 3])

In [ ]:
v2

array([4, 5, 6])

In [ ]:
np.dot(v1,v2)

np.int64(32)

In [ ]:
v = np.array([1,2,3,4,5])
norm = np.linalg.norm(v)

print(norm)

v/norm

7.416198487095663


array([0.13483997, 0.26967994, 0.40451992, 0.53935989, 0.67419986])

In [ ]:
v1 = np.array([1,0,0])
v2 = np.array([0,1,0])

np.dot(v1, v2)

np.int64(0)

In [ ]:
v = np.array([1,2,3,2,4,5,3])

np.unique(v)

array([1, 2, 3, 4, 5])

In [ ]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

print(v1 - v2)
print(v2 - v1)
print(v1 + v2)
print(v2 + v1)
print(v1 * v2)
print(v2 * v1)
print(v1 / v2)
print(v2 / v1)

[-3 -3 -3]
[3 3 3]
[5 7 9]
[5 7 9]
[ 4 10 18]
[ 4 10 18]
[0.25 0.4  0.5 ]
[4.  2.5 2. ]


In [ ]:
vector = np.array([1,2,3,4,5])
length = np.linalg.norm(vector)

length

np.float64(7.416198487095663)

In [ ]:
np.isclose(length, 5)


np.False_

In [ ]:
a = np.random.randint(0,11,(3,3))
a

array([[ 6, 10,  8],
       [ 6, 10,  3],
       [ 7,  2,  4]])

In [ ]:
np.linalg.det(a)

np.float64(-289.99999999999994)

In [ ]:
np.linalg.inv(a)

array([[-0.11724138,  0.08275862,  0.17241379],
       [ 0.01034483,  0.11034483, -0.10344828],
       [ 0.2       , -0.2       ,  0.        ]])

In [ ]:
a = np.array([[1,3,-4],[0,2,-3],[-2,2,5]])
b = np.array([5,3,4])

x= np.linalg.solve(a,b)
print('Вбудована функція', x.round(1))

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print('Матричний метод', x1.round(1))

Вбудована функція [0.4 1.8 0.2]
Матричний метод [0.4 1.8 0.2]


In [ ]:
print(a.T)
print(b.T)

[[ 1  0 -2]
 [ 3  2  2]
 [-4 -3  5]]
[5 3 4]


In [ ]:
print(np.transpose(a))
print(np.transpose(b))

[[ 1  0 -2]
 [ 3  2  2]
 [-4 -3  5]]
[5 3 4]


In [ ]:
matrix = np.matrix([[2,2,2],[2,2,2],[2,2,2]])

np.allclose(matrix, matrix.T)

True

In [ ]:
np.trace(matrix)

np.int64(6)

In [ ]:
b = np.matrix([[5,3,4],[2,3,5],[3,2,3]])
print(b)
print(np.sort(b,axis=0))
print(np.sort(b,axis=1))
print(np.sort(b,axis=None))

[[5 3 4]
 [2 3 5]
 [3 2 3]]
[[2 2 3]
 [3 3 4]
 [5 3 5]]
[[3 4 5]
 [2 3 5]
 [2 3 3]]
[[2 2 3 3 3 3 4 5 5]]


In [ ]:
a = np.array([[1,4],[3,1]])
print(a)
print(np.sort(a))

[[1 4]
 [3 1]]
[[1 4]
 [1 3]]


In [ ]:
print(np.sort(a, axis=0))
print(np.sort(a, axis=1))

[[1 1]
 [3 4]]
[[1 4]
 [1 3]]
